import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "ABC Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en" data-theme="dark">
    <html lang="en" data-theme="light">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
